import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://www.pldtglobal.com/en/enterprise/edge-and-security")
    page.get_by_role("link", name="Enterprise", exact=True).click()
    expect(page.get_by_role("heading", name="Edge and Security Solutions")).to_be_visible()
    expect(page.get_by_text("Enterprise-grade edge and")).to_be_visible()
    expect(page.locator("section").filter(has_text="Back to").locator("img")).to_be_visible()
    expect(page.locator(".flex-shrink-0").first).to_be_visible()
    expect(page.locator("div").filter(has_text="Content Delivery Network (CDN").nth(2)).to_be_visible()
    expect(page.get_by_text("Content Delivery Network (CDN)Deliver content at scale on PLDT’s globally")).to_be_visible()
    expect(page.locator(".relative.mb-6").first).to_be_visible()
    expect(page.get_by_role("heading", name="Content Delivery Network (CDN)")).to_be_visible()
    expect(page.get_by_text("Deliver content at scale on")).to_be_visible()
    expect(page.get_by_text("Endpoint & Cloud SecuritySecure endpoints and cloud workloads through PLDT’s")).to_be_visible()
    expect(page.locator("div:nth-child(3) > .gradient-border-card > .relative")).to_be_visible()
    expect(page.get_by_role("heading", name="Endpoint & Cloud Security")).to_be_visible()
    expect(page.get_by_text("Secure endpoints and cloud")).to_be_visible()
    expect(page.locator("div:nth-child(2) > .gradient-border-card > .relative")).to_be_visible()
    expect(page.get_by_role("heading", name="Network Security")).to_be_visible()
    expect(page.get_by_text("Protect enterprise networks")).to_be_visible()
    expect(page.locator("div:nth-child(5) > .gradient-border-card > .relative")).to_be_visible()
    expect(page.get_by_role("heading", name="Authentication and Fraud")).to_be_visible()
    expect(page.get_by_text("trengthen digital trust using")).to_be_visible()
    expect(page.get_by_text("Cloud and Web EdgeOptimize")).to_be_visible()
    expect(page.locator("div:nth-child(4) > .gradient-border-card > .relative")).to_be_visible()
    expect(page.get_by_role("heading", name="Cloud and Web Edge")).to_be_visible()
    expect(page.get_by_text("Optimize global web and cloud")).to_be_visible()
    expect(page.get_by_text("IP eXchangeA private, quality")).to_be_visible()
    expect(page.locator("div:nth-child(6) > .gradient-border-card > .relative")).to_be_visible()
    expect(page.get_by_role("heading", name="IP eXchange")).to_be_visible()
    expect(page.get_by_text("A private, quality-assured IP")).to_be_visible()
