import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://www.pldtglobal.com/en/enterprise/pgc-global-connectivity")
    page.get_by_role("link", name="Enterprise", exact=True).click()
    expect(page.get_by_role("heading", name="Global Connectivity")).to_be_visible()
    expect(page.get_by_text("Scalable, secure, and high-")).to_be_visible()
    expect(page.locator("section").filter(has_text="Back to").locator("img")).to_be_visible()
    expect(page.get_by_role("heading", name="Your Global Connection, Made")).to_be_visible()
    expect(page.get_by_role("paragraph").filter(has_text="A portfolio of internet and")).to_be_visible()
    expect(page.locator("img").nth(2)).to_be_visible()
    expect(page.locator(".flex-shrink-0").first).to_be_visible()
    expect(page.locator("div").filter(has_text="Fiber Internet for").nth(2)).to_be_visible()
    expect(page.get_by_text("Fiber Internet for BusinessHigh-speed, low-latency fiber connectivity designed")).to_be_visible()
    expect(page.locator(".relative.mb-6").first).to_be_visible()
    expect(page.get_by_role("heading", name="Fiber Internet for Business")).to_be_visible()
    expect(page.get_by_text("High-speed, low-latency fiber")).to_be_visible()
    expect(page.locator("div:nth-child(3) > .gradient-border-card > .relative")).to_be_visible()
    expect(page.get_by_role("heading", name="Dedicated Internet Access")).to_be_visible()
    expect(page.get_by_text("Premium uncontended bandwidth")).to_be_visible()
    expect(page.get_by_role("heading", name="Satellite Internet")).to_be_visible()
    expect(page.locator("div:nth-child(5) > .gradient-border-card > .relative")).to_be_visible()
    expect(page.get_by_role("heading", name="International Ethernet")).to_be_visible()
    expect(page.get_by_text("LAN-to-LAN interconnection")).to_be_visible()
    expect(page.locator("div:nth-child(4) > .gradient-border-card > .relative")).to_be_visible()
    expect(page.get_by_text("International Private Leased CircuitPrivate point-to-point connectivity between")).to_be_visible()
    expect(page.get_by_role("heading", name="International Private Leased")).to_be_visible()
    expect(page.get_by_text("Private point-to-point")).to_be_visible()
    expect(page.get_by_text("IP Transit and HubbingAggregated, scalable global backbone access for optimized")).to_be_visible()
    expect(page.locator("div:nth-child(7) > .gradient-border-card > .relative")).to_be_visible()
    expect(page.get_by_role("heading", name="IP Transit and Hubbing")).to_be_visible()
    expect(page.get_by_text("Aggregated, scalable global")).to_be_visible()
    expect(page.get_by_text("iGateA carrier-grade internet")).to_be_visible()
    expect(page.get_by_role("heading", name="iGate")).to_be_visible()
    expect(page.get_by_text("A carrier-grade internet")).to_be_visible()
    expect(page.locator("div:nth-child(8) > .gradient-border-card > .relative")).to_be_visible()
