import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://hayopnimanam.com/menu/?current_menu=menu-1")
    expect(page.get_by_text("the menu", exact=True)).to_be_visible()
    expect(page.get_by_text("behind the taste")).to_be_visible()
    expect(page.get_by_label("2 /").get_by_text("a la carte")).to_be_visible()
    expect(page.get_by_text("main menu")).to_be_visible()
    expect(page.get_by_label("3 /").get_by_text("lunch sets")).to_be_visible()
    expect(page.get_by_text("tsibog combo")).to_be_visible()
    expect(page.get_by_label("4 /").get_by_text("dessert")).to_be_visible()
    expect(page.get_by_text("minatamis")).to_be_visible()
    expect(page.get_by_text("drinks")).to_be_visible()
    expect(page.get_by_label("5 /").get_by_text("inumin")).to_be_visible()
    expect(page.get_by_role("heading", name="panimula pica")).to_be_visible()
    expect(page.get_by_text("Kinilaw 28 P")).to_be_visible()
    expect(page.get_by_text("Kuruma ebi, green chilies,")).to_be_visible()
    expect(page.get_by_text("Lumpia 14 V")).to_be_visible()
    expect(page.get_by_text("Roasted heirloom baby carrots")).to_be_visible()
    expect(page.get_by_text("Sisig Tokwa 18 V")).to_be_visible()
    expect(page.get_by_text("Crispy tofu, diced and")).to_be_visible()
    expect(page.get_by_text("Chicharon Bulaklak")).to_be_visible()
    expect(page.get_by_text("Deep-fried pork ruffle fat,")).to_be_visible()
    expect(page.get_by_text("Manam’s House Crispy Sisig")).to_be_visible()
    expect(page.get_by_text("Pork jowl and cheek, chopped")).to_be_visible()
    expect(page.get_by_role("paragraph").filter(has_text="Manam’s Crispy Palabok")).to_be_visible()
    expect(page.get_by_text("Charred baby cuttlefi sh &")).to_be_visible()
    expect(page.get_by_role("heading", name="gulay vegetables")).to_be_visible()
    expect(page.get_by_text("Ensaladang Hayop 18 P")).to_be_visible()
    expect(page.get_by_text("Green mango, winged bean, red")).to_be_visible()
    expect(page.get_by_text("Watermelon Atsara 3 VG")).to_be_visible()
    expect(page.get_by_text("Local house-made relish of")).to_be_visible()
    expect(page.get_by_text("Gising Gising 18 P")).to_be_visible()
    expect(page.get_by_role("paragraph").filter(has_text="Winged bean and tofu crumble")).to_be_visible()
    expect(page.get_by_text("Adobong Gulay 18 V")).to_be_visible()
    expect(page.get_by_role("paragraph").filter(has_text="Sautéed kale Spinach, garlic")).to_be_visible()
    expect(page.get_by_text("Laing 18 P")).to_be_visible()
    expect(page.get_by_text("Taro leaves in coconut Bagoong, fi sh sauce, bird’s eye chili")).to_be_visible()
    expect(page.get_by_role("paragraph").filter(has_text="Wild Mushroom & Tofu Kare-")).to_be_visible()
    expect(page.get_by_text("Maitake, Portobello, King Oyster, fried tofu and tofu pillows, in a peanut and")).to_be_visible()
    expect(page.get_by_role("heading", name="ulam mains")).to_be_visible()
    expect(page.get_by_role("paragraph").filter(has_text="Adobong Dilaw")).to_be_visible()
    expect(page.get_by_text("Grain-fed Duroc pork belly Turmeric, sukang tuba, ginger, calamansi, and")).to_be_visible()
    expect(page.get_by_role("paragraph").filter(has_text="Golden fried Grain-fed Duroc")).to_be_visible()
    expect(page.get_by_role("paragraph").filter(has_text="Lechon Kawali")).to_be_visible()
    expect(page.get_by_role("listitem").filter(has_text="Piyanggang Manok")).to_be_visible()
    expect(page.get_by_text("Charcoal-grilled then braised")).to_be_visible()
    expect(page.get_by_text("Midnight Adobo")).to_be_visible()
    expect(page.get_by_text("Slow-braised Australian beef")).to_be_visible()
    expect(page.get_by_text("Rellenong Pusit 26 P")).to_be_visible()
    expect(page.get_by_text("Grilled whole squid, milkfish")).to_be_visible()
    expect(page.get_by_text("Inasal na Panga 39/42 P")).to_be_visible()
    expect(page.get_by_role("paragraph").filter(has_text="Charcoal-grilled maguro jaw")).to_be_visible()
    expect(page.get_by_text("Charcoal-roasted Ulang in")).to_be_visible()
    expect(page.get_by_text("Grilled river prawns Aligue,")).to_be_visible()
    expect(page.get_by_text("Crab Bicol Express 35 P")).to_be_visible()
    expect(page.get_by_text("Fried Softshell and Swimmer")).to_be_visible()
    expect(page.get_by_text("Oxtail & Tripe Kare-Kare")).to_be_visible()
    expect(page.get_by_text("Grass-fed Brazilian oxtail")).to_be_visible()
    expect(page.get_by_text("Pork & Pineapple Sinigang")).to_be_visible()
    expect(page.get_by_text("Grain-fed Duroc pork belly Grilled pineapples, French beans, kangkong, eggplant")).to_be_visible()
    expect(page.get_by_text("Manam’s Wagyu & Watermelon")).to_be_visible()
    expect(page.get_by_text("AUS Wagyu short rib, 300g")).to_be_visible()
    expect(page.get_by_text("Spatchcock Chicken Inasal")).to_be_visible()
    expect(page.get_by_text("Charcoal-grilled corn-fed heritage French spring chicken Annatto, calamansi,")).to_be_visible()
    expect(page.get_by_text("Spicy Lechon Belly*")).to_be_visible()
    expect(page.get_by_text("Brined then roasted pork")).to_be_visible()
    expect(page.get_by_text("Lechon de Leche**")).to_be_visible()
    expect(page.get_by_text("Slow-roasted whole suckling")).to_be_visible()
    expect(page.get_by_text("* PRE-ORDER 48 HOURS IN")).to_be_visible()
    expect(page.get_by_role("heading", name="kanin rice")).to_be_visible()
    expect(page.get_by_text("Kanin 3 VG")).to_be_visible()
    expect(page.get_by_text("Fragrant jasmine rice", exact=True)).to_be_visible()
    expect(page.get_by_text("Unli-Kanin 5 VG")).to_be_visible()
    expect(page.get_by_text("Eat-all-you-can fragrant")).to_be_visible()
    expect(page.get_by_text("Sinangag 7 VG")).to_be_visible()
    expect(page.get_by_text("Rice stir-fried in garlic")).to_be_visible()
    expect(page.get_by_text("Bagoong Rice 10 P")).to_be_visible()
    expect(page.get_by_text("Rice sautéed in our fermented")).to_be_visible()
    expect(page.get_by_text("Bone Marrow Sinangag")).to_be_visible()
    expect(page.get_by_text("Rice stir fried in garlic and")).to_be_visible()
