import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://hayopnimanam.com/menu/?current_menu=menu-3")
    expect(page.get_by_text("the menu", exact=True)).to_be_visible()
    expect(page.get_by_text("behind the taste")).to_be_visible()
    expect(page.get_by_label("2 /").get_by_text("a la carte")).to_be_visible()
    expect(page.get_by_text("main menu")).to_be_visible()
    expect(page.get_by_label("3 /").get_by_text("lunch sets")).to_be_visible()
    expect(page.get_by_text("tsibog combo")).to_be_visible()
    expect(page.get_by_label("4 /").get_by_text("dessert")).to_be_visible()
    expect(page.get_by_text("minatamis")).to_be_visible()
    expect(page.get_by_text("drinks")).to_be_visible()
    expect(page.get_by_label("5 /").get_by_text("inumin")).to_be_visible()
    expect(page.get_by_role("heading", name="dessert")).to_be_visible()
    expect(page.get_by_role("paragraph").filter(has_text="a la carte")).to_be_visible()
    expect(page.get_by_text("Halo-halo")).to_be_visible()
    expect(page.get_by_text("Shaved ice, ube halaya, nata")).to_be_visible()
    expect(page.get_by_text("Mais con Hielo")).to_be_visible()
    expect(page.get_by_text("Shaved ice, sweet corn milk,")).to_be_visible()
    expect(page.get_by_text("Manam’s Ube Shake")).to_be_visible()
    expect(page.get_by_text("Housemade purple yam sorbetes, coconut cream, white sago", exact=True)).to_be_visible()
    expect(page.get_by_text("Turon 14")).to_be_visible()
    expect(page.get_by_role("paragraph").filter(has_text="Crisp caramelized banana")).to_be_visible()
    expect(page.get_by_text("Buko Pie")).to_be_visible()
    expect(page.get_by_text("Coconut and parmesan crumble")).to_be_visible()
    expect(page.get_by_text("Patis Caramel Tart")).to_be_visible()
    expect(page.get_by_text("Dark chocolate ganache with")).to_be_visible()
    expect(page.get_by_text("Manam's Buko Pandan Shake 15")).to_be_visible()
    expect(page.get_by_text("House coconut blend, white sago, and green pandan gulaman", exact=True)).to_be_visible()
    expect(page.get_by_text("Sorbetes 6")).to_be_visible()
    expect(page.get_by_text("House-made ice cream Ube")).to_be_visible()
