import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://hayopnimanam.com/menu/?current_menu=menu-4")
    expect(page.get_by_role("heading", name="alcoholic inuman")).to_be_visible()
    expect(page.get_by_text("Cocktails 22 $")).to_be_visible()
    expect(page.get_by_text("Alat | Salty Tequila, Fresh")).to_be_visible()
    expect(page.get_by_text("Asim | Sour Sloe Gin,")).to_be_visible()
    expect(page.get_by_text("Tamis | Sweet Sake, Chamomile")).to_be_visible()
    expect(page.get_by_text("Anghang | Spicy Vodka,")).to_be_visible()
    expect(page.get_by_text("Malinamnam | Umami Coconut")).to_be_visible()
    expect(page.get_by_text("Pait | Bitter Dark Rum, Decaf")).to_be_visible()
    expect(page.get_by_text("Philippine Beers")).to_be_visible()
    expect(page.get_by_role("listitem").filter(has_text="San Miguel Light 15 $")).to_be_visible()
    expect(page.get_by_role("listitem").filter(has_text="Engkanto 18 $")).to_be_visible()
    expect(page.get_by_role("listitem").filter(has_text="Wines & Sakes")).to_be_visible()
    expect(page.get_by_role("listitem").filter(has_text="Please ask for our")).to_be_visible()
    expect(page.get_by_role("heading", name="non-alcoholic inumin")).to_be_visible()
    expect(page.get_by_text("Shakes 15 $")).to_be_visible()
    expect(page.get_by_text("Manam's Ube Shake Housemade")).to_be_visible()
    expect(page.get_by_text("Manam's Buko Pandan Shake House coconut blend, white sago, and green pandan")).to_be_visible()
    expect(page.get_by_text("Canned Sodas 6 $")).to_be_visible()
    expect(page.get_by_text("Coca-Cola")).to_be_visible()
    expect(page.get_by_text("Sprite")).to_be_visible()
    expect(page.get_by_text("Coffee", exact=True)).to_be_visible()
    expect(page.get_by_text("Espresso 4.5 $")).to_be_visible()
    expect(page.get_by_text("Black Coffee 5 $")).to_be_visible()
    expect(page.get_by_text("Flat White 6 $")).to_be_visible()
    expect(page.get_by_text("Latte 6 $")).to_be_visible()
    expect(page.get_by_text("Cappuccino 6 $")).to_be_visible()
    expect(page.get_by_role("listitem").filter(has_text="Tea 6 $")).to_be_visible()
    expect(page.get_by_text("Oolong Tea")).to_be_visible()
    expect(page.get_by_text("Green Tea")).to_be_visible()
    expect(page.get_by_text("Chamomile Tea")).to_be_visible()
