import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://hayopnimanam.com/menu/?current_menu=menu-2")
    expect(page.get_by_text("the menu", exact=True)).to_be_visible()
    expect(page.get_by_text("behind the taste")).to_be_visible()
    expect(page.get_by_label("2 /").get_by_text("a la carte")).to_be_visible()
    expect(page.get_by_text("main menu")).to_be_visible()
    expect(page.get_by_label("3 /").get_by_text("lunch sets")).to_be_visible()
    expect(page.get_by_text("tsibog combo")).to_be_visible()
    expect(page.get_by_label("4 /").get_by_text("dessert")).to_be_visible()
    expect(page.get_by_text("minatamis")).to_be_visible()
    expect(page.get_by_text("drinks")).to_be_visible()
    expect(page.get_by_label("5 /").get_by_text("inumin")).to_be_visible()
    expect(page.get_by_role("heading", name="lunch sets")).to_be_visible()
    expect(page.get_by_text("comes with your choice of")).to_be_visible()
    expect(page.locator("span").filter(has_text="Lechon Kawali")).to_be_visible()
    expect(page.get_by_role("paragraph").filter(has_text="Golden fried Grain-fed Duroc")).to_be_visible()
    expect(page.get_by_text("Inihaw na Baboy")).to_be_visible()
    expect(page.get_by_text("Oven-braised then Charcoal-")).to_be_visible()
    expect(page.get_by_text("Adobong Pula")).to_be_visible()
    expect(page.get_by_text("Corn-fed heritage French chicken and fried chicken flakes Sukang Sasa, toyo,")).to_be_visible()
    expect(page.locator("span").filter(has_text="Adobong Dilaw")).to_be_visible()
    expect(page.get_by_text("Grain-fed Duroc pork belly Turmeric, sukang tuba, ginger, calamansi", exact=True)).to_be_visible()
    expect(page.get_by_text("Chicken Inasal 29")).to_be_visible()
    expect(page.get_by_text("Charcoal-grilled corn-fed heritage French spring half chicken Annatto,")).to_be_visible()
    expect(page.get_by_text("Inasal na Panga 36 P")).to_be_visible()
    expect(page.get_by_role("paragraph").filter(has_text="Charcoal-grilled maguro jaw")).to_be_visible()
    expect(page.locator("span").filter(has_text="Manam’s Crispy Palabok")).to_be_visible()
    expect(page.get_by_text("Charred baby cuttlefish,")).to_be_visible()
    expect(page.get_by_text("Manam’s Tapsilog")).to_be_visible()
    expect(page.get_by_text("Manam’s house-cured Angus")).to_be_visible()
    expect(page.locator("span").filter(has_text="Wild Mushroom & Tofu Kare-")).to_be_visible()
    expect(page.get_by_text("Maitake, Portobello, King Oyster, fried tofu and tofu pillow Peanut and miso")).to_be_visible()
    expect(page.get_by_role("heading", name="top up")).to_be_visible()
    expect(page.get_by_text("+$7 for vegetable or dessert")).to_be_visible()
    expect(page.get_by_text("choice of vegetables")).to_be_visible()
    expect(page.get_by_text("Gising Gising P")).to_be_visible()
    expect(page.get_by_role("paragraph").filter(has_text="Winged bean and tofu crumble")).to_be_visible()
    expect(page.get_by_text("Laing P")).to_be_visible()
    expect(page.get_by_text("Taro leaves in coconut Bagoong, fish sauce, bird’s eye chili")).to_be_visible()
    expect(page.get_by_role("paragraph").filter(has_text="Sautéed kale Spinach, garlic")).to_be_visible()
    expect(page.get_by_text("Adobong Gulay P")).to_be_visible()
    expect(page.get_by_text("choice of dessert")).to_be_visible()
    expect(page.get_by_text("Turon", exact=True)).to_be_visible()
    expect(page.get_by_role("paragraph").filter(has_text="Crisp caramelized banana")).to_be_visible()
    expect(page.get_by_text("Ensaymada")).to_be_visible()
    expect(page.get_by_text("Warm house-made brioche")).to_be_visible()
