"""
Locators for the Hayop signup flow (https://hayop.atlas.kitchen/signup).

CAUTION: PATH_NTH_2 uses a positional <path> SVG element selector
(.nth(2)). This is fragile -- SVG path order can change with any icon
library update. Kept 1:1 with codegen; replace with a stable
aria-label or parent-scoped locator when possible.

CAUTION: TITLE_SELECT is Ant Design's internal rc_select_0 id. This
ID is generated by Ant Design's Select component and may change if
new Select components are added to the page before this one.
Replace with a label/aria-label scoped selector if one becomes
available.
"""


class SignupLocators:

    SIGNUP_URL = "https://hayop.atlas.kitchen/signup"

    # --- Header / Nav ---
    LINK_HAYOP            = "role=link[name='Hayop']"
    BTN_ORDER_NOW         = "role=button[name='Order now']"

    @staticmethod
    def path_nth_2(page):
        """
        CAUTION: positional SVG path selector -- fragile, see module
        docstring. Likely targets a back/close/menu icon in the header.
        """
        return page.locator("path").nth(2)

    # --- Initial Signup Page ---
    @staticmethod
    def heading_sign_up(page):
        return page.get_by_role("heading", name="Sign up for a Hayop account")

    TEXT_FASTER_CHECKOUTS = "text=Get faster checkouts, order"
    TEXT_ALREADY_HAVE_ACCOUNT = "text=Already have an account? Log"
    INPUT_LABEL_TESTID    = "[data-testid='input-label']"
    PHONE_INPUT           = "role=textbox[name='Contact number']"
    PHONE_COUNTRY_SELECT  = "role=combobox"  # get_by_label("Phone number country")
    BTN_SIGN_UP           = "role=button[name='Sign up']"
    TEXT_OR               = "text=or"  # exact
    BTN_CONTINUE_EMAIL    = "role=button[name='Continue with email']"
    POWERED_BY_ATLAS      = "#poweredByAtlasId"

    LINK_LOG_IN_HERE      = "role=link[name='Log in here']"

    @staticmethod
    def phone_country_select(page):
        return page.get_by_label("Phone number country")

    @staticmethod
    def phone_input(page):
        return page.get_by_role("textbox", name="Contact number")

    # --- Detailed Signup Form (after phone submit) ---
    TEXT_EMAIL_REQUIRED   = "text=Email addressRequired"
    EMAIL_INPUT           = "role=textbox[name='Enter your email']"
    TEXT_NAME_EXACT       = "text=Name"  # exact
    TEXT_NAME_REQUIRED    = "text=NameRequired"
    NAME_INPUT            = "role=textbox[name='Name']"

    @staticmethod
    def div_title(page):
        import re
        return page.locator("div").filter(has_text=re.compile(r"^Title$"))

    @staticmethod
    def div_address_title(page):
        import re
        return page.locator("div").filter(
            has_text=re.compile(r"^How should we address you\?$")
        ).nth(1)

    TEXT_DATE_OF_BIRTH    = "text=Date of birth"
    BIRTHDAY_INPUT        = "role=textbox[name='When is your birthday?']"
    ANT_PICKER            = ".ant-picker"

    # CAUTION: Ant Design internal ID -- see module docstring.
    TITLE_SELECT          = "#rc_select_0"

    TEXT_CONSENT          = "text=I consent to receiving"
    # Fixed: role= string syntax requires exact full accessible name match.
    # Full name from DOM: "I consent to receiving exclusive discounts,
    # seasonal specials, and latest updates via email."
    # Use get_by_role with partial name instead.
    @staticmethod
    def checkbox_consent(page):
        return page.get_by_role("checkbox", name="I consent to receiving")
    TEXT_BY_CONTINUING    = "text=By continuing, you agree to"
    BTN_SIGN_UP_FOR_ACCOUNT = "role=button[name='Sign up for an account']"

    # --- Birthday Picker ---
    @staticmethod
    def btn_year_panel(page):
        return page.get_by_role("button", name="year panel")

    @staticmethod
    def btn_super_prev_year(page):
        return page.get_by_role("button", name="super-prev-year")

    # --- OTP Modal ---
    @staticmethod
    def otp_dialog(page):
        return page.get_by_role("dialog").filter(
            has_text="CloseSign up with 6-digit"
        ).get_by_role("dialog")

    TEXT_OTP_HEADING      = "text=Sign up with 6-digit code"
    TEXT_OTP_INSTRUCTION  = "text=Enter the code sent to SMS to"

    @staticmethod
    def otp_input(page, n: int):
        """n is 1-indexed (1–6), matching the OTP character positions."""
        return page.get_by_role(
            "spinbutton", name=f"Please enter OTP character {n}"
        )

    TEXT_CODE_SENT        = "text=Code sent to phone +"
    TEXT_RESEND           = "text=Resend"
    TEXT_CODE_RESENT      = "text=Code resent to phone +"
    BTN_CLOSE_MODAL       = "role=button[name='Close']"  # exact

    @staticmethod
    def powered_by_atlas_in_dialog(page):
        return page.get_by_role("dialog").filter(
            has_text="CloseSign up with 6-digit"
        ).locator("#poweredByAtlasId")

    # --- Footer Links (open in popup) ---
    LINK_TERMS_OF_SERVICE = "role=link[name='terms of service']"
    LINK_PRIVACY_POLICY   = "role=link[name='privacy policy']"